# Generated by Django 4.1.6 on 2023-03-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_shorturl_clicks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='clicks',
            new_name='num_clicks',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
