# Generated by Django 4.1.6 on 2023-03-02 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_rename_clicks_shorturl_num_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
